
import type { VocabularyWord } from './types';

export const commonWords: VocabularyWord[] = [
    // Verbs (Sein, Haben, Werden)
    { type: 'verb', german: 'sein', russian: 'быть', conjugation: 'ich bin, du bist, er ist', example: 'Ich bin müde.' },
    { type: 'verb', german: 'haben', russian: 'иметь', conjugation: 'ich habe, du hast, er hat', example: 'Ich habe eine Frage.' },
    { type: 'verb', german: 'werden', russian: 'становиться', conjugation: 'ich werde, du wirst, er wird', example: 'Es wird kalt.' },

    // Modal Verbs
    { type: 'verb', german: 'können', russian: 'мочь, уметь', conjugation: 'ich kann, du kannst, er kann', example: 'Ich kann schwimmen.' },
    { type: 'verb', german: 'müssen', russian: 'быть должным', conjugation: 'ich muss, du musst, er muss', example: 'Ich muss jetzt gehen.' },
    { type: 'verb', german: 'wollen', russian: 'хотеть', conjugation: 'ich will, du willst, er will', example: 'Ich will ein Eis.' },
    { type: 'verb', german: 'sollen', russian: 'быть должным (совет)', conjugation: 'ich soll, du sollst, er soll', example: 'Du sollst mehr schlafen.' },
    { type: 'verb', german: 'dürfen', russian: 'мочь (иметь разрешение)', conjugation: 'ich darf, du darfst, er darf', example: 'Hier darf man nicht rauchen.' },
    { type: 'verb', german: 'mögen', russian: 'любить, нравиться', conjugation: 'ich mag, du magst, er mag', example: 'Ich mag Schokolade.' },

    // Common Verbs (Expanded to 100 total)
    { type: 'verb', german: 'machen', russian: 'делать', conjugation: 'ich mache, du machst', example: 'Was machst du?' },
    { type: 'verb', german: 'gehen', russian: 'идти', conjugation: 'ich gehe, du gehst', example: 'Ich gehe ins Kino.' },
    { type: 'verb', german: 'kommen', russian: 'приходить', conjugation: 'ich komme, du kommst', example: 'Kommst du mit?' },
    { type: 'verb', german: 'sprechen', russian: 'говорить', conjugation: 'ich spreche, du sprichst', example: 'Sprichst du Deutsch?' },
    { type: 'verb', german: 'sagen', russian: 'сказать', conjugation: 'ich sage, du sagst', example: 'Was hast du gesagt?' },
    { type: 'verb', german: 'sehen', russian: 'видеть', conjugation: 'ich sehe, du siehst', example: 'Ich sehe einen Vogel.' },
    { type: 'verb', german: 'hören', russian: 'слышать, слушать', conjugation: 'ich höre, du hörst', example: 'Ich höre gerne Musik.' },
    { type: 'verb', german: 'lesen', russian: 'читать', conjugation: 'ich lese, du liest', example: 'Ich lese ein Buch.' },
    { type: 'verb', german: 'schreiben', russian: 'писать', conjugation: 'ich schreibe, du schreibst', example: 'Ich schreibe eine E-Mail.' },
    { type: 'verb', german: 'essen', russian: 'есть', conjugation: 'ich esse, du isst', example: 'Ich esse eine Pizza.' },
    { type: 'verb', german: 'trinken', russian: 'пить', conjugation: 'ich trinke, du trinkst', example: 'Ich trinke einen Kaffee.' },
    { type: 'verb', german: 'geben', russian: 'давать', conjugation: 'ich gebe, du gibst', example: 'Gib mir bitte das Buch.' },
    { type: 'verb', german: 'nehmen', russian: 'брать', conjugation: 'ich nehme, du nimmst', example: 'Ich nehme den Bus.' },
    { type: 'verb', german: 'fahren', russian: 'ехать', conjugation: 'ich fahre, du fährst', example: 'Ich fahre mit dem Auto.' },
    { type: 'verb', german: 'finden', russian: 'находить', conjugation: 'ich finde, du findest', example: 'Ich finde meine Schlüssel nicht.' },
    { type: 'verb', german: 'bleiben', russian: 'оставаться', conjugation: 'ich bleibe, du bleibst', example: 'Ich bleibe heute zu Hause.' },
    { type: 'verb', german: 'arbeiten', russian: 'работать', conjugation: 'ich arbeite, du arbeitest', example: 'Ich arbeite als Lehrer.' },
    { type: 'verb', german: 'leben', russian: 'жить', conjugation: 'ich lebe, du lebst', example: 'Ich lebe in Berlin.' },
    { type: 'verb', german: 'fragen', russian: 'спрашивать', conjugation: 'ich frage, du fragst', example: 'Ich frage den Lehrer.' },
    { type: 'verb', german: 'antworten', russian: 'отвечать', conjugation: 'ich antworte, du antwortest', example: 'Bitte antworte auf meine Frage.' },
    { type: 'verb', german: 'helfen', russian: 'помогать', conjugation: 'ich helfe, du hilfst', example: 'Kannst du mir helfen?' },
    { type: 'verb', german: 'kaufen', russian: 'покупать', conjugation: 'ich kaufe, du kaufst', example: 'Ich kaufe Brot.' },
    { type: 'verb', german: 'verkaufen', russian: 'продавать', conjugation: 'ich verkaufe, du verkaufst', example: 'Er verkauft sein Auto.' },
    { type: 'verb', german: 'verstehen', russian: 'понимать', conjugation: 'ich verstehe, du verstehst', example: 'Ich verstehe das nicht.' },
    { type: 'verb', german: 'beginnen', russian: 'начинать', conjugation: 'ich beginne, du beginnst', example: 'Der Film beginnt um 20 Uhr.' },
    { type: 'verb', german: 'denken', russian: 'думать', conjugation: 'ich denke, du denkst', example: 'Ich denke an dich.' },
    { type: 'verb', german: 'wissen', russian: 'знать', conjugation: 'ich weiß, du weißt', example: 'Ich weiß das nicht.' },
    { type: 'verb', german: 'lernen', russian: 'учить', conjugation: 'ich lerne, du lernst', example: 'Ich lerne Deutsch.' },
    { type: 'verb', german: 'schlafen', russian: 'спать', conjugation: 'ich schlafe, du schläfst', example: 'Ich schlafe acht Stunden.' },
    { type: 'verb', german: 'stehen', russian: 'стоять', conjugation: 'ich stehe, du stehst', example: 'Das Auto steht vor dem Haus.' },
    { type: 'verb', german: 'sitzen', russian: 'сидеть', conjugation: 'ich sitze, du sitzt', example: 'Wir sitzen im Café.' },
    { type: 'verb', german: 'liegen', russian: 'лежать', conjugation: 'ich liege, du liegst', example: 'Das Buch liegt auf dem Tisch.' },
    { type: 'verb', german: 'kennen', russian: 'знать (кого-то, что-то)', conjugation: 'ich kenne, du kennst', example: 'Ich kenne diesen Mann.' },
    { type: 'verb', german: 'bringen', russian: 'приносить', conjugation: 'ich bringe, du bringst', example: 'Ich bringe dir einen Kaffee.' },
    { type: 'verb', german: 'laufen', russian: 'бежать', conjugation: 'ich laufe, du läufst, er läuft', example: 'Ich laufe jeden Morgen im Park.' },
    { type: 'verb', german: 'meinen', russian: 'иметь в виду, полагать', conjugation: 'ich meine, du meinst', example: 'Was meinst du damit?' },
    { type: 'verb', german: 'glauben', russian: 'верить, полагать', conjugation: 'ich glaube, du glaubst', example: 'Ich glaube, es wird regnen.' },
    { type: 'verb', german: 'halten', russian: 'держать, останавливаться', conjugation: 'ich halte, du hältst, er hält', example: 'Der Bus hält hier.' },
    { type: 'verb', german: 'nennen', russian: 'называть', conjugation: 'ich nenne, du nennst', example: 'Wie nennt man das auf Deutsch?' },
    { type: 'verb', german: 'zeigen', russian: 'показывать', conjugation: 'ich zeige, du zeigst', example: 'Kannst du mir den Weg zeigen?' },
    { type: 'verb', german: 'führen', russian: 'вести, руководить', conjugation: 'ich führe, du führst', example: 'Sie führt das Unternehmen erfolgreich.' },
    { type: 'verb', german: 'brauchen', russian: 'нуждаться', conjugation: 'ich brauche, du brauchst', example: 'Ich brauche deine Hilfe.' },
    { type: 'verb', german: 'folgen', russian: 'следовать', conjugation: 'ich folge, du folgst', example: 'Folgen Sie mir bitte.' },
    { type: 'verb', german: 'spielen', russian: 'играть', conjugation: 'ich spiele, du spielst', example: 'Die Kinder spielen draußen.' },
    { type: 'verb', german: 'versuchen', russian: 'пытаться, пробовать', conjugation: 'ich versuche, du versuchst', example: 'Ich versuche, Deutsch zu lernen.' },
    { type: 'verb', german: 'erzählen', russian: 'рассказывать', conjugation: 'ich erzähle, du erzählst', example: 'Erzähl mir eine Geschichte.' },
    { type: 'verb', german: 'warten', russian: 'ждать', conjugation: 'ich warte, du wartest', example: 'Ich warte auf den Bus.' },
    { type: 'verb', german: 'verlieren', russian: 'терять', conjugation: 'ich verliere, du verlierst', example: 'Ich habe meine Schlüssel verloren.' },
    { type: 'verb', german: 'gewinnen', russian: 'выигрывать', conjugation: 'ich gewinne, du gewinnst', example: 'Unsere Mannschaft hat das Spiel gewonnen.' },
    { type: 'verb', german: 'schließen', russian: 'закрывать', conjugation: 'ich schließe, du schließt', example: 'Bitte schließe die Tür.' },
    { type: 'verb', german: 'öffnen', russian: 'открывать', conjugation: 'ich öffne, du öffnest', example: 'Öffnen Sie bitte das Fenster.' },
    { type: 'verb', german: 'bezahlen', russian: 'платить', conjugation: 'ich bezahle, du bezahlst', example: 'Ich bezahle mit Karte.' },
    { type: 'verb', german: 'bestellen', russian: 'заказывать', conjugation: 'ich bestelle, du bestellst', example: 'Wir bestellen eine Pizza.' },
    { type: 'verb', german: 'besuchen', russian: 'посещать', conjugation: 'ich besuche, du besuchst', example: 'Ich besuche meine Großeltern.' },
    { type: 'verb', german: 'treffen', russian: 'встречать', conjugation: 'ich treffe, du triffst, er trifft', example: 'Ich treffe heute meine Freunde.' },
    { type: 'verb', german: 'erklären', russian: 'объяснять', conjugation: 'ich erkläre, du erklärst', example: 'Kannst du mir die Regel erklären?' },
    { type: 'verb', german: 'erhalten', russian: 'получать', conjugation: 'ich erhalte, du erhältst, er erhält', example: 'Ich habe eine E-Mail erhalten.' },
    { type: 'verb', german: 'studieren', russian: 'учиться (в вузе)', conjugation: 'ich studiere, du studierst', example: 'Sie studiert Medizin.' },
    { type: 'verb', german: 'vergessen', russian: 'забывать', conjugation: 'ich vergesse, du vergisst, er vergisst', example: 'Ich habe meinen Schirm vergessen.' },
    { type: 'verb', german: 'erinnern', russian: 'помнить, напоминать', conjugation: 'ich erinnere, du erinnerst', example: 'Ich erinnere mich an diesen Tag.' },
    { type: 'verb', german: 'entscheiden', russian: 'решать', conjugation: 'ich entscheide, du entscheidest', example: 'Ich kann mich nicht entscheiden.' },
    { type: 'verb', german: 'anbieten', russian: 'предлагать', conjugation: 'ich biete an, du bietest an', example: 'Darf ich Ihnen einen Kaffee anbieten?' },
    { type: 'verb', german: 'tragen', russian: 'носить, нести', conjugation: 'ich trage, du trägst, er trägt', example: 'Er trägt eine Brille.' },
    { type: 'verb', german: 'ziehen', russian: 'тянуть, переезжать', conjugation: 'ich ziehe, du ziehst', example: 'Wir ziehen nächste Woche um.' },
    { type: 'verb', german: 'fallen', russian: 'падать', conjugation: 'ich falle, du fällst, er fällt', example: 'Die Blätter fallen von den Bäumen.' },
    { type: 'verb', german: 'gehören', russian: 'принадлежать', conjugation: 'ich gehöre, du gehörst', example: 'Wem gehört dieses Buch?' },
    { type: 'verb', german: 'entstehen', russian: 'возникать', conjugation: 'es entsteht', example: 'Wie entsteht ein Regenbogen?' },
    { type: 'verb', german: 'sterben', russian: 'умирать', conjugation: 'ich sterbe, du stirbst, er stirbt', example: 'Alle Menschen müssen sterben.' },
    { type: 'verb', german: 'lieben', russian: 'любить', conjugation: 'ich liebe, du liebst', example: 'Ich liebe dich.' },
    { type: 'verb', german: 'hassen', russian: 'ненавидеть', conjugation: 'ich hasse, du hasst', example: 'Ich hasse es, früh aufzustehen.' },
    { type: 'verb', german: 'waschen', russian: 'мыть, стирать', conjugation: 'ich wasche, du wäschst, er wäscht', example: 'Ich muss meine Wäsche waschen.' },
    { type: 'verb', german: 'kochen', russian: 'готовить (еду)', conjugation: 'ich koche, du kochst', example: 'Heute koche ich Pasta.' },
    { type: 'verb', german: 'backen', russian: 'печь', conjugation: 'ich backe, du bäckst, er bäckt', example: 'Sie backt einen Kuchen.' },
    { type: 'verb', german: 'fliegen', russian: 'летать', conjugation: 'ich fliege, du fliegst', example: 'Wir fliegen nach Spanien.' },
    { type: 'verb', german: 'reisen', russian: 'путешествовать', conjugation: 'ich reise, du reist', example: 'Ich reise gern.' },
    { type: 'verb', german: 'tanzen', russian: 'танцевать', conjugation: 'ich tanze, du tanzt', example: 'Sie tanzt sehr gut.' },
    { type: 'verb', german: 'singen', russian: 'петь', conjugation: 'ich singe, du singst', example: 'Er singt in einem Chor.' },
    { type: 'verb', german: 'lachen', russian: 'смеяться', conjugation: 'ich lache, du lachst', example: 'Wir haben viel gelacht.' },
    { type: 'verb', german: 'weinen', russian: 'плакать', conjugation: 'ich weine, du weinst', example: 'Das Baby weint.' },
    { type: 'verb', german: 'hoffen', russian: 'надеяться', conjugation: 'ich hoffe, du hoffst', example: 'Ich hoffe, du kommst bald.' },
    { type: 'verb', german: 'fühlen', russian: 'чувствовать', conjugation: 'ich fühle, du fühlst', example: 'Wie fühlst du dich?' },
    { type: 'verb', german: 'riechen', russian: 'пахнуть, нюхать', conjugation: 'ich rieche, du riechst', example: 'Die Blumen riechen gut.' },
    { type: 'verb', german: 'schmecken', russian: 'быть на вкус', conjugation: 'es schmeckt', example: 'Das Essen schmeckt lecker.' },
    { type: 'verb', german: 'planen', russian: 'планировать', conjugation: 'ich plane, du planst', example: 'Wir planen unseren Urlaub.' },
    { type: 'verb', german: 'probieren', russian: 'пробовать', conjugation: 'ich probiere, du probierst', example: 'Möchtest du das probieren?' },
    { type: 'verb', german: 'reparieren', russian: 'чинить', conjugation: 'ich repariere, du reparierst', example: 'Er repariert das Auto.' },
    { type: 'verb', german: 'stören', russian: 'мешать', conjugation: 'ich störe, du störst', example: 'Bitte stör mich nicht.' },
    { type: 'verb', german: 'zerstören', russian: 'разрушать', conjugation: 'ich zerstöre, du zerstörst', example: 'Der Sturm hat das Haus zerstört.' },
    { type: 'verb', german: 'aufwachen', russian: 'просыпаться', conjugation: 'ich wache auf', example: 'Ich wache jeden Tag um 7 Uhr auf.' },
    { type: 'verb', german: 'einschlafen', russian: 'засыпать', conjugation: 'ich schlafe ein', example: 'Ich kann nicht einschlafen.' },
    { type: 'verb', german: 'anrufen', russian: 'звонить', conjugation: 'ich rufe an', example: 'Ich rufe dich später an.' },
    { type: 'verb', german: 'einkaufen', russian: 'делать покупки', conjugation: 'ich kaufe ein', example: 'Wir kaufen im Supermarkt ein.' },
    { type: 'verb', german: 'mitbringen', russian: 'приносить с собой', conjugation: 'ich bringe mit', example: 'Ich bringe einen Kuchen mit.' },
    { type: 'verb', german: 'teilnehmen', russian: 'участвовать', conjugation: 'ich nehme teil', example: 'Ich nehme am Wettbewerb teil.' },
    { type: 'verb', german: 'vorschlagen', russian: 'предлагать', conjugation: 'ich schlage vor', example: 'Ich schlage vor, dass wir ins Kino gehen.' },

    // Conjunctions (Full List)
    { type: 'conjunction', german: 'und', russian: 'и', structure: 'Сочинит. союз. Не меняет порядок слов.', example: 'Ich trinke Kaffee und esse Kuchen.' },
    { type: 'conjunction', german: 'sowie', russian: 'а также, как и', structure: 'Сочинит. союз. Не меняет порядок слов.', example: 'Ich brauche Äpfel, Birnen sowie Bananen.' },
    { type: 'conjunction', german: 'aber', russian: 'но', structure: 'Сочинит. союз. Не меняет порядок слов.', example: 'Ich will schlafen, aber ich muss arbeiten.' },
    { type: 'conjunction', german: 'sondern', russian: 'а (при противопоставлении)', structure: 'Сочинит. союз. Используется после отрицания, не меняет порядок слов.', example: 'Das ist nicht schwarz, sondern weiß.' },
    { type: 'conjunction', german: 'doch', russian: 'однако, но', structure: 'Сочинит. союз. Не меняет порядок слов.', example: 'Er ist müde, doch er arbeitet weiter.' },
    { type: 'conjunction', german: 'oder', russian: 'или', structure: 'Сочинит. союз. Не меняет порядок слов.', example: 'Möchtest du Tee oder Kaffee?' },
    { type: 'conjunction', german: 'denn', russian: 'так как, потому что', structure: 'Сочинит. союз. Не меняет порядок слов.', example: 'Ich bleibe zu Hause, denn ich bin krank.' },
    { type: 'other', german: 'bloß', russian: 'только, лишь', structure: 'Частица, обычно перед тем, что ограничивает.', example: 'Wenn ich bloß mehr Zeit hätte!'},
    { type: 'other', german: 'nur', russian: 'только, лишь', structure: 'Наречие.', example: 'Ich habe nur 5 Euro.'},
    { type: 'conjunction', german: 'weil', russian: 'потому что', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich lerne Deutsch, weil ich in Deutschland arbeiten will.' },
    { type: 'conjunction', german: 'da', russian: 'так как (часто в начале)', structure: 'Подчинит. союз. Глагол в конце.', example: 'Da ich krank bin, bleibe ich heute zu Hause.'},
    { type: 'conjunction', german: 'zumal', russian: 'тем более что', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich gehe nicht aus, zumal ich kein Geld habe.'},
    { type: 'conjunction', german: 'als', russian: 'когда (в прошлом, однократно)', structure: 'Подчинит. союз. Глагол в конце.', example: 'Als ich ein Kind war, spielte ich viel.' },
    { type: 'conjunction', german: 'wenn', russian: 'когда, если', structure: 'Подчинит. союз. Глагол в конце.', example: 'Wenn ich Zeit habe, komme ich.' },
    { type: 'other', german: 'wann', russian: 'когда (в вопросах)', structure: 'Вопросительное слово. Прямой или косвенный вопрос.', example: 'Wann kommst du? Ich weiß nicht, wann er kommt.'},
    { type: 'conjunction', german: 'während', russian: 'в то время как', structure: 'Подчинит. союз. Глагол в конце.', example: 'Während ich koche, hört er Musik.' },
    { type: 'conjunction', german: 'nachdem', russian: 'после того как', structure: 'Подчинит. союз. Глагол в конце.', example: 'Nachdem ich gegessen hatte, ging ich spazieren.' },
    { type: 'conjunction', german: 'bevor', russian: 'перед тем как', structure: 'Подчинит. союз. Глагол в конце.', example: 'Bevor du gehst, ruf mich an.' },
    { type: 'conjunction', german: 'ehe', russian: 'прежде чем', structure: 'Подчинит. союз. Глагол в конце. (Синоним bevor)', example: 'Ehe wir gehen, müssen wir aufräumen.'},
    { type: 'conjunction', german: 'seit', russian: 'с тех пор как', structure: 'Подчинит. союз. Глагол в конце.', example: 'Seit ich in Berlin wohne, fahre ich viel Fahrrad.' },
    { type: 'conjunction', german: 'seitdem', russian: 'с тех пор как', structure: 'Подчинит. союз. Глагол в конце. (Синоним seit)', example: 'Seitdem er hier arbeitet, ist die Stimmung besser.'},
    { type: 'conjunction', german: 'bis', russian: 'пока не', structure: 'Подчинит. союз. Глагол в конце.', example: 'Warte hier, bis ich zurückkomme.' },
    { type: 'conjunction', german: 'solange', russian: 'пока', structure: 'Подчинит. союз. Глагол в конце.', example: 'Solange du hier bist, ist alles gut.'},
    { type: 'conjunction', german: 'sobald', russian: 'как только', structure: 'Подчинит. союз. Глагол в конце.', example: 'Sobald ich zu Hause bin, rufe ich dich an.'},
    { type: 'conjunction', german: 'falls', russian: 'в случае если', structure: 'Подчинит. союз. Глагол в конце.', example: 'Falls es regnet, bleiben wir drinnen.'},
    { type: 'conjunction', german: 'sofern', russian: 'если, поскольку', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich komme mit, sofern ich Zeit habe.'},
    { type: 'conjunction', german: 'damit', russian: 'чтобы', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich lerne Deutsch, damit ich in Deutschland studieren kann.' },
    { type: 'conjunction', german: 'dass', russian: 'что', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich weiß, dass du kommst.' },
    { type: 'conjunction', german: 'sodass', russian: 'так что (результат)', structure: 'Подчинит. союз. Глагол в конце.', example: 'Er hat gelernt, sodass er die Prüfung bestanden hat.'},
    { type: 'conjunction', german: 'obwohl', russian: 'хотя', structure: 'Подчинит. союз. Глагол в конце.', example: 'Er geht spazieren, obwohl es regnet.' },
    { type: 'conjunction', german: 'obgleich', russian: 'хотя', structure: 'Подчинит. союз. Глагол в конце. (Синоним obwohl)', example: 'Obgleich er müde war, arbeitete er weiter.'},
    { type: 'conjunction', german: 'obschon', russian: 'хотя', structure: 'Подчинит. союз. Глагол в конце. (Устаревший синоним obwohl)', example: 'Er kam, obschon ich es ihm verboten hatte.'},
    { type: 'conjunction', german: 'auch wenn', russian: 'даже если', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich komme, auch wenn ich wenig Zeit habe.'},
    { type: 'conjunction', german: 'wenngleich', russian: 'хотя, пусть даже', structure: 'Подчинит. союз. Глагол в конце. (Синоним obwohl)', example: 'Er ist ein guter Freund, wenngleich er manchmal schwierig ist.'},
    { type: 'conjunction', german: 'wie', russian: 'как', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich weiß nicht, wie das funktioniert.' },
    { type: 'conjunction', german: 'je ... desto', russian: 'чем ... тем', structure: 'Парный союз. Придаточное с "je" (глагол в конце), главное с "desto" (глагол сразу после).', example: 'Je mehr man lernt, desto mehr weiß man.' },
    { type: 'conjunction', german: 'ob', russian: 'ли', structure: 'Подчинит. союз. Глагол в конце.', example: 'Ich weiß nicht, ob er kommt.' },
    { type: 'conjunction', german: 'deshalb', russian: 'поэтому', structure: 'Союзное наречие. Обратный порядок слов (глагол на 2-м месте).', example: 'Ich war krank, deshalb bin ich nicht gekommen.' },
    { type: 'conjunction', german: 'deswegen', russian: 'поэтому, из-за этого', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Das Wetter war schlecht, deswegen sind wir zu Hause geblieben.'},
    { type: 'conjunction', german: 'daher', russian: 'поэтому, следовательно', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Er hat nicht gelernt, daher hat er die Prüfung nicht bestanden.'},
    { type: 'conjunction', german: 'darum', russian: 'потому', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Ich mag dich, darum helfe ich dir.'},
    { type: 'conjunction', german: 'trotzdem', russian: 'несмотря на это', structure: 'Союзное наречие. Обратный порядок слов (глагол на 2-м месте).', example: 'Es regnet, trotzdem gehen wir spazieren.' },
    { type: 'conjunction', german: 'dennoch', russian: 'тем не менее', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Er war müde, dennoch arbeitete er weiter.'},
    { type: 'conjunction', german: 'jedoch', russian: 'однако', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Das Hotel ist teuer, jedoch bietet es viel Komfort.'},
    { type: 'conjunction', german: 'außerdem', russian: 'кроме того', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Das Essen ist lecker, außerdem ist der Service gut.'},
    { type: 'conjunction', german: 'zudem', russian: 'к тому же', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Der Film war langweilig, zudem waren die Schauspieler schlecht.'},
    { type: 'conjunction', german: 'folglich', russian: 'следовательно', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Er hat gelogen, folglich kann man ihm nicht vertrauen.'},
    { type: 'conjunction', german: 'somit', russian: 'таким образом', structure: 'Союзное наречеи. Обратный порядок слов.', example: 'Die Prüfung war bestanden, somit war das Studium beendet.'},
    { type: 'conjunction', german: 'sonst', russian: 'иначе, а то', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Beeil dich, sonst verpassen wir den Zug.'},
    { type: 'conjunction', german: 'andernfalls', russian: 'в противном случае', structure: 'Союзное наречие. Обратный порядок слов.', example: 'Du musst die Rechnung bezahlen, andernfalls gibt es Probleme.'},
    { type: 'conjunction', german: 'nicht nur … sondern auch', russian: 'не только … но и', structure: 'Парный союз.', example: 'Er ist nicht nur klug, sondern auch sehr freundlich.'},
    { type: 'conjunction', german: 'sowohl ... als auch', russian: 'как ... так и', structure: 'Парный союз. Не меняет порядок слов.', example: 'Er mag sowohl Tee als auch Kaffee.' },
    { type: 'conjunction', german: 'weder ... noch', russian: 'ни ... ни', structure: 'Парный союз. Не меняет порядок слов.', example: 'Ich habe weder Zeit noch Geld.' },
    { type: 'conjunction', german: 'entweder ... oder', russian: 'или ... или', structure: 'Парный союз. Соединяет однородные члены или предложения.', example: 'Wir können entweder ins Kino gehen oder zu Hause bleiben.' },
    { type: 'conjunction', german: 'zwar ... aber', russian: 'хотя ... но', structure: 'Парный союз. Соединяет два главных предложения.', example: 'Er ist zwar reich, aber nicht glücklich.' },
    
    // Prepositions + Dativ
    { type: 'preposition', case: 'Dativ', german: 'mit', russian: 'с', example: 'Ich fahre mit dem Bus.' },
    { type: 'preposition', case: 'Dativ', german: 'nach', russian: 'после, в (направление)', example: 'Nach der Arbeit gehe ich nach Hause.' },
    { type: 'preposition', case: 'Dativ', german: 'aus', russian: 'из', example: 'Er kommt aus Spanien.' },
    { type: 'preposition', case: 'Dativ', german: 'zu', russian: 'к', example: 'Ich gehe zum Arzt.' },
    { type: 'preposition', case: 'Dativ', german: 'von', russian: 'от, о', example: 'Das ist ein Geschenk von meiner Mutter.' },
    { type: 'preposition', case: 'Dativ', german: 'bei', russian: 'у, при', example: 'Ich wohne bei meinen Eltern.' },
    
    // Prepositions + Akkusativ
    { type: 'preposition', case: 'Akkusativ', german: 'für', russian: 'для', example: 'Das Geschenk ist für dich.' },
    { type: 'preposition', case: 'Akkusativ', german: 'ohne', russian: 'без', example: 'Ich trinke Kaffee ohne Zucker.' },
    { type: 'preposition', case: 'Akkusativ', german: 'durch', russian: 'через, сквозь', example: 'Wir gehen durch den Park.' },
    { type: 'preposition', case: 'Akkusativ', german: 'gegen', russian: 'против', example: 'Ich bin gegen diese Idee.' },
    { type: 'preposition', case: 'Akkusativ', german: 'um', russian: 'вокруг, в (о времени)', example: 'Wir sitzen um den Tisch. Der Film beginnt um 20 Uhr.' },
    
    // Wechselpräpositionen
    { type: 'preposition', case: 'Wechselpräposition', german: 'in', russian: 'в', example: 'Ich bin in der Schule. / Ich gehe in die Schule.' },
    { type: 'preposition', case: 'Wechselpräposition', german: 'an', russian: 'на (вертикально), у, к', example: 'Das Bild hängt an der Wand. / Ich gehe an das Fenster.' },
    { type: 'preposition', case: 'Wechselpräposition', german: 'auf', russian: 'на (горизонтально)', example: 'Das Buch liegt auf dem Tisch. / Ich lege das Buch auf den Tisch.' },
    
    // Common Nouns
    { type: 'noun', german: 'Zeit', russian: 'время', article: 'die', plural: 'Zeiten', pluralArticle: 'die', exampleSingular: 'Ich habe keine Zeit.', examplePlural: 'Das waren gute Zeiten.' },
    { type: 'noun', german: 'Tag', russian: 'день', article: 'der', plural: 'Tage', pluralArticle: 'die', exampleSingular: 'Heute ist ein schöner Tag.', examplePlural: 'Die Woche hat sieben Tage.' },
    { type: 'noun', german: 'Woche', russian: 'неделя', article: 'die', plural: 'Wochen', pluralArticle: 'die', exampleSingular: 'Diese Woche habe ich viel Arbeit.', examplePlural: 'Ich fahre für zwei Wochen weg.' },
    { type: 'noun', german: 'Jahr', russian: 'год', article: 'das', plural: 'Jahre', pluralArticle: 'die', exampleSingular: 'Das Jahr hat 365 Tage.', examplePlural: 'Ich lebe seit 10 Jahren hier.' },
    { type: 'noun', german: 'Mensch', russian: 'человек', article: 'der', plural: 'Menschen', pluralArticle: 'die', exampleSingular: 'Der Mensch ist ein soziales Wesen.', examplePlural: 'Alle Menschen sind gleich.' },
    { type: 'noun', german: 'Mann', russian: 'мужчина', article: 'der', plural: 'Männer', pluralArticle: 'die', exampleSingular: 'Der Mann liest eine Zeitung.', examplePlural: 'Dort stehen zwei Männer.' },
    { type: 'noun', german: 'Frau', russian: 'женщина', article: 'die', plural: 'Frauen', pluralArticle: 'die', exampleSingular: 'Die Frau trinkt Kaffee.', examplePlural: 'Die Frauen unterhalten sich.' },
    { type: 'noun', german: 'Kind', russian: 'ребенок', article: 'das', plural: 'Kinder', pluralArticle: 'die', exampleSingular: 'Das Kind spielt im Garten.', examplePlural: 'Die Kinder sind in der Schule.' },
    { type: 'noun', german: 'Leben', russian: 'жизнь', article: 'das', plural: 'Leben', pluralArticle: 'die', exampleSingular: 'Das Leben ist schön.', examplePlural: 'Die Leben vieler Menschen haben sich verändert.' },
    { type: 'noun', german: 'Arbeit', russian: 'работа', article: 'die', plural: 'Arbeiten', pluralArticle: 'die', exampleSingular: 'Die Arbeit macht Spaß.', examplePlural: 'Er hat viele wissenschaftliche Arbeiten geschrieben.' },
    { type: 'noun', german: 'Stadt', russian: 'город', article: 'die', plural: 'Städte', pluralArticle: 'die', exampleSingular: 'Berlin ist eine große Stadt.', examplePlural: 'Ich besuche gerne alte Städte.' },
    { type: 'noun', german: 'Land', russian: 'страна', article: 'das', plural: 'Länder', pluralArticle: 'die', exampleSingular: 'Deutschland ist ein schönes Land.', examplePlural: 'Ich bin in viele Länder gereist.' },
    { type: 'noun', german: 'Welt', russian: 'мир', article: 'die', plural: 'Welten', pluralArticle: 'die', exampleSingular: 'Die Welt ist groß.', examplePlural: 'Es gibt verschiedene Welten in diesem Buch.' },
    { type: 'noun', german: 'Schule', russian: 'школа', article: 'die', plural: 'Schulen', pluralArticle: 'die', exampleSingular: 'Die Schule beginnt um 8 Uhr.', examplePlural: 'Es gibt viele gute Schulen hier.' },
    { type: 'noun', german: 'Haus', russian: 'дом', article: 'das', plural: 'Häuser', pluralArticle: 'die', exampleSingular: 'Mein Haus ist weiß.', examplePlural: 'Die Häuser in dieser Straße sind alt.' },
    { type: 'noun', german: 'Auto', russian: 'машина', article: 'das', plural: 'Autos', pluralArticle: 'die', exampleSingular: 'Ich fahre mit dem Auto.', examplePlural: 'Auf der Straße sind viele Autos.' },
    { type: 'noun', german: 'Wasser', russian: 'вода', article: 'das', plural: 'Wässer', pluralArticle: 'die', exampleSingular: 'Ich trinke ein Glas Wasser.', examplePlural: 'Heilende Wässer kommen aus der Quelle.' },
    { type: 'noun', german: 'Frage', russian: 'вопрос', article: 'die', plural: 'Fragen', pluralArticle: 'die', exampleSingular: 'Ich habe eine Frage.', examplePlural: 'Habt ihr noch Fragen?' },
    { type: 'noun', german: 'Antwort', russian: 'ответ', article: 'die', plural: 'Antworten', pluralArticle: 'die', exampleSingular: 'Die Antwort ist einfach.', examplePlural: 'Ich warte auf deine Antworten.' },
    
    // Adjectives & Adverbs
    { type: 'adjective', german: 'gut', russian: 'хороший', comparative: 'besser', superlative: 'am besten', example: 'Das Essen ist gut.' },
    { type: 'adjective', german: 'schlecht', russian: 'плохой', comparative: 'schlechter', superlative: 'am schlechtesten', example: 'Das Wetter ist heute schlecht.' },
    { type: 'adjective', german: 'groß', russian: 'большой', comparative: 'größer', superlative: 'am größten', example: 'Ein großer Baum steht im Garten.' },
    { type: 'adjective', german: 'klein', russian: 'маленький', comparative: 'kleiner', superlative: 'am kleinsten', example: 'Das ist ein kleines Haus.' },
    { type: 'adjective', german: 'neu', russian: 'новый', comparative: 'neuer', superlative: 'am neuesten', example: 'Ich habe ein neues Fahrrad.' },
    { type: 'adjective', german: 'alt', russian: 'старый', comparative: 'älter', superlative: 'am ältesten', example: 'Mein Opa ist schon sehr alt.' },
    { type: 'adjective', german: 'richtig', russian: 'правильный', comparative: 'richtiger', superlative: 'am richtigsten', example: 'Das ist die richtige Antwort.' },
    { type: 'adjective', german: 'falsch', russian: 'неправильный', comparative: 'falscher', superlative: 'am falschesten', example: 'Diese Information ist falsch.' },
    { type: 'other', german: 'sehr', russian: 'очень', example: 'Das ist sehr interessant.' },
    { type: 'other', german: 'nicht', russian: 'не', example: 'Ich verstehe das nicht.' },
    { type: 'other', german: 'auch', russian: 'также', example: 'Ich komme auch mit.' },
    { type: 'other', german: 'hier', russian: 'здесь', example: 'Wir wohnen hier.' },
    { type: 'other', german: 'dort', russian: 'там', example: 'Dort ist der Bahnhof.' },
    { type: 'other', german: 'jetzt', russian: 'сейчас', example: 'Ich muss jetzt gehen.' },
    { type: 'other', german: 'immer', russian: 'всегда', example: 'Er ist immer pünktlich.' },
    { type: 'other', german: 'nie', russian: 'никогда', example: 'Ich war noch nie in Japan.' },
    { type: 'other', german: 'oft', russian: 'часто', example: 'Wir gehen oft ins Kino.' },
    { type: 'other', german: 'manchmal', russian: 'иногда', example: 'Manchmal esse ich Pizza.' },
  ];

    
